# Configuration for https://travis-ci.org/

language: go
dist: bionic

go_import_path: blitiri.com.ar/go/systemd

go:
    - 1.9
    - stable
    - master

script:
    - go test ./...
    - go test -race ./...
